name: Build Poetry Package on Multiple Platforms

on:
  workflow_dispatch:

jobs:
  build-sdist:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build package (sdist)
        run: poetry build -f sdist

      - name: Upload built sdist package
        uses: actions/upload-artifact@v4
        with:
          name: engine-package-sdist-py${{ matrix.python-version }}-${{ github.workflow_sha }}
          path: artefacts/build/${{ github.workflow_sha }}/

  build-wheel:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build package (wheel)
        run: poetry build -f wheel

      - name: Upload built wheel package
        uses: actions/upload-artifact@v4
        with:
          name: engine-package-wheel-${{ matrix.os }}-py${{ matrix.python-version }}-${{ github.workflow_sha }}
          path: artefacts/build/${{ github.workflow_sha }}/
