name: Build Poetry Package on Multiple Platforms

on:
  workflow_dispatch:

jobs:
  build-sdist:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build package (sdist)
        run: poetry build -f sdist

      - name: Get Git commit hash
        id: git_hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create directory for artefacts
        run: mkdir -p artefacts/build/${{ github.workflow_sha }}

      - name: Move built sdist package to artefacts directory
        run: mv dist/*.tar.gz artefacts/build/${{ github.workflow_sha }}/

      - name: Push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add .
          git commit -m "Add artefacts for commit ${{ github.workflow_sha }}"
          git push origin HEAD:master
      

      - name: Upload built sdist package
        uses: actions/upload-artifact@v4
        with:
          name: engine-package-sdist-py${{ matrix.python-version }}-${{ github.workflow_sha }}
          path: artefacts/build/${{ github.workflow_sha }}/

  build-wheel:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build package (wheel)
        run: poetry build -f wheel

      - name: Get Git commit hash
        id: git_hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create directory for artefacts
        run: mkdir -p artefacts/build/${{ github.workflow_sha }}

      - name: Move built wheel package to artefacts directory
        run: mv dist/*.whl artefacts/build/${{ github.workflow_sha }}/

      - name: Push build
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add .
          git commit -m "Add artefacts for commit ${{ github.workflow_sha }}"
          git push origin HEAD:master
      

      - name: Upload built wheel package
        uses: actions/upload-artifact@v4
        with:
          name: engine-package-wheel-${{ matrix.os }}-py${{ matrix.python-version }}-${{ github.workflow_sha }}
          path: artefacts/build/${{ github.workflow_sha }}/
