name: Build Poetry Package on Multiple Platforms

on:
  workflow_dispatch:

jobs:
  build-sdist:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build package (sdist)
        run: poetry build -f sdist

      - name: Get Git commit hash
        id: git_hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create directory for artefacts
        run: mkdir -p artefacts/build/${{ github.sha }}

      - name: Move built sdist package to artefacts directory
        run: mv dist/*.tar.gz artefacts/build/${{ github.sha }}/

      - name: Commit changes (if any)
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add artefacts/
          git diff --cached --quiet || git commit -m "Add artefacts for commit ${{ github.sha }}"
      
      - name: Push changes
        run: |
          git push origin HEAD:master

      - name: Upload built sdist package
        uses: actions/upload-artifact@v4
        with:
          name: engine-package-sdist-py${{ matrix.python-version }}-${{ github.sha }}
          path: artefacts/build/${{ github.sha }}/

  build-wheel:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build package (wheel)
        run: poetry build -f wheel

      - name: Get Git commit hash
        id: git_hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create directory for artefacts
        run: mkdir -p artefacts/build/${{ github.sha }}

      - name: Move built wheel package to artefacts directory
        run: mv dist/*.whl artefacts/build/${{ github.sha }}/

      - name: Commit changes (if any)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git add artefacts/
          git diff --cached --quiet || git commit -m "Add artefacts for commit ${{ github.sha }}"

      - name: Push changes
        run: |
          git push origin HEAD:master

      - name: Upload built wheel package
        uses: actions/upload-artifact@v4
        with:
          name: engine-package-wheel-${{ matrix.os }}-py${{ matrix.python-version }}-${{ github.sha }}
          path: artefacts/build/${{ github.sha }}/
