name: Commit Messages
on: [pull_request_target]

jobs:
  commit-msg:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/first-interaction@v1
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            issue-message: 'Commit Messages'
            pr-message: 'Commit Messages'